/* ============================================================
   data.js — All portfolio content data
   Edit this file to update your portfolio!
   ============================================================ */

const PORTFOLIO_DATA = {

  // ── Personal Info ─────────────────────────────────────────
  personal: {
    name: "Md. Mehedi Hasan Shuvo",
    shortName: "MH Shuvo",
    title: "AI Engineer & Researcher",
    email: "mdmehedihasanshuvo994@gmail.com",
    phone: "+8801954-596854",
    location: "Kuratoli, Khilkhet, Dhaka 1229, Bangladesh",
    github: "https://github.com/MH-SHUVO20",
    linkedin: "https://www.linkedin.com/in/mh-shuvo-aiub/",
    portfolio: "https://mhshuvo.me/",
    facebook: "https://www.facebook.com/mh.shuvo.7370",
    // Place your photo at assets/img/avatar.jpg
    avatar: "assets/img/avatar.jpg",
    // Place your resume PDF at assets/resume/Md_Mehedi_Hasan_Shuvo_Resume.pdf
    resumePDF: "assets/resume/Md_Mehedi_Hasan_Shuvo_Resume.pdf",
    typedStrings: [
      "Computer Vision Engineer",
      "Deep Learning Researcher",
      "LLM & Agent Systems Builder",
      "IEEE Published Author",
      "YOLO Architecture Specialist",
      "Open to Internship & Full-time Roles",
    ],
  },

  // ── Skills ─────────────────────────────────────────────────
  skills: [
    {
      icon: "🧠",
      cat: "ai",
      category: "Deep Learning & CV",
      title: "Computer Vision",
      tags: ["YOLO Models", "CNN", "Transformers", "Object Detection", "Image Classification", "Transfer Learning", "Model Optimization"]
    },
    {
      icon: "🕹️",
      cat: "ai",
      category: "Neural Networks",
      title: "Deep Neural Networks",
      tags: [
        "Feedforward Neural Networks (FNN)",
        "Convolutional Neural Networks (CNN)",
        "Recurrent Neural Networks (RNN)",
        "Long Short-Term Memory (LSTM)",
        "Gated Recurrent Unit (GRU)",
        "Transformer Architecture",
        "Vision Transformer (ViT)",
        "Generative Adversarial Networks (GAN)",
        "Variational Autoencoders (VAE)",
        "Graph Neural Networks (GNN)",
        "Attention Mechanisms & Self-Attention",
        "Batch Normalization & Dropout",
        "Residual Networks (ResNet)",
        "Backpropagation & Gradient Descent",
        "Multi-Task Learning"
      ]
    },
    {
      icon: "💬",
      cat: "ai",
      category: "NLP & Text AI",
      title: "Natural Language Processing",
      tags: [
        "Tokenization & Text Preprocessing",
        "Word Embeddings (Word2Vec · GloVe · FastText)",
        "BERT & Transformer Fine-tuning",
        "Sentiment Analysis",
        "Named Entity Recognition (NER)",
        "Text Classification",
        "Question Answering Systems",
        "Sequence-to-Sequence Models",
        "Retrieval-Augmented Generation (RAG)",
        "Semantic Search & Embeddings",
        "Topic Modeling (LDA)",
        "Text Summarization",
        "Language Model Evaluation (BLEU · ROUGE)",
        "Multilingual NLP"
      ]
    },
    {
      icon: "🤖",
      cat: "ai",
      category: "LLMs & Agents",
      title: "LLM & Agent Systems",
      tags: ["LangChain", "LangGraph", "Prompt Engineering", "OpenAI API", "Ollama", "Multi-Agent Systems", "Tool Calling", "ReAct Agents", "Memory Management", "Chain-of-Thought Prompting"]
    },
    {
      icon: "📊",
      cat: "ai",
      category: "Machine Learning",
      title: "Classical ML",
      tags: [
        "Supervised & Unsupervised Learning",
        "XGBoost / LightGBM / CatBoost",
        "SVM & Kernel Methods",
        "Bayesian Optimization",
        "Ensemble & Boosting Methods",
        "Dimensionality Reduction (PCA · t-SNE · UMAP)",
        "Anomaly Detection",
        "Hyperparameter Tuning (Optuna)",
        "Cross-Validation & Regularization",
        "Feature Engineering & Selection",
        "Time Series Forecasting (LSTM · ARIMA)",
        "Class Imbalance Handling (SMOTE)",
        "AutoML Pipelines"
      ]
    },
    {
      icon: "⚡",
      cat: "ai",
      category: "Frameworks",
      title: "ML Libraries",
      tags: ["PyTorch", "TensorFlow", "Keras", "HuggingFace Transformers", "OpenCV", "Scikit-learn", "Pandas", "NumPy", "Matplotlib"]
    },
    {
      icon: "🌐",
      cat: "eng",
      category: "Web & Backend",
      title: "Engineering",
      tags: ["FastAPI", "Docker", "Redis", "REST APIs", "PHP", "MVC Architecture", "AJAX/JSON", "Session Management", "RBAC"]
    },
    {
      icon: "🗄️",
      cat: "eng",
      category: "Databases",
      title: "Data & Storage",
      tags: ["MySQL", "Oracle", "SQLite", "Relational Schema Design", "3NF Normalization", "Query Optimization", "SQL Injection Prevention"]
    },
    {
      icon: "💻",
      cat: "lang",
      category: "Programming",
      title: "Languages",
      tags: ["Python (Primary)", "C#", "Java", "R", "C++", "C", "HTML5", "CSS3", "JavaScript", "LaTeX"]
    },
    {
      icon: "🛠️",
      cat: "tools",
      category: "Dev Tools",
      title: "Tools & Platforms",
      tags: ["Jupyter Notebook", "Google Colab", "Git", "GitHub", "Docker", "VS Code", "Kaggle", "R Studio", "Matlab", "LaTeX"]
    },
    {
      icon: "🔬",
      cat: "tools",
      category: "Research Practices",
      title: "Research Skills",
      tags: ["Experimental Design", "Model Benchmarking", "IEEE Paper Writing", "Peer Review", "mAP/F1 Evaluation", "Reproducibility", "Systematic Benchmarking"]
    },
    {
      icon: "🏫",
      cat: "tools",
      category: "Teaching & Mentorship",
      title: "Tutoring & Education",
      tags: [
        "6+ Years Teaching Experience",
        "English Medium (4+ Years)",
        "One-to-One & Group Tutoring",
        "Online & In-Person",
        "Physics · Chemistry · Biology",
        "Mathematics & Higher Maths",
        "Additional Mathematics",
        "Computer Science & ICT",
        "English & Bangla Literature",
        "O Level & A Level Preparation",
        "SSC & HSC Coaching",
        "Class 6–12 All Subjects",
        "Disciplined Study Habit Building",
        "Goal Setting & Student Motivation",
        "Coaching Center Co-Management (500+ Students)",
        "Long-Term Student Mentorship"
      ]
    },
  ],

  // ── Skill Proficiency Bars ─────────────────────────────────
  proficiency: [
    { name: "Computer Vision", pct: 92 },
    { name: "Machine Learning", pct: 91 },
    { name: "Python & PyTorch", pct: 90 },
    { name: "LangChain / LangGraph", pct: 82 },
    { name: "BERT & NLP", pct: 80 },
    { name: "FastAPI & Docker", pct: 75 },
    { name: "Research Skills",       pct: 88 },
    { name: "Tutoring & Mentorship",  pct: 95 },
  ],

  // ── Publications ────────────────────────────────────────────
  research: [
    {
      num: "01",
      title: "Deep Learning Based Real-Time Hand Detection Using First-Person Egocentric Perspectives",
      venue: "IEEE/ACS AICCSA 2025 — 22nd Int'l Conference on Computer Systems and Applications",
      badges: ["CORE RANKED", "Published"],
      link: "https://ieeexplore.ieee.org/document/11315447",
      doi: "10.1109/AICCSA66935.2025.11315447",
    },
    {
      num: "02",
      title: "A Deep Learning-Based Framework for Accurate Detection and Classification of On-Road Vehicles Using Improved YOLOv11",
      venue: "IEEE ECCE 2025 — Int'l Conference on Electrical, Computer and Communication Engineering",
      badges: ["Published"],
      link: "https://ieeexplore.ieee.org/document/11013964",
      doi: "10.1109/ECCE64574.2025.11013964",
    },
    {
      num: "03",
      title: "DBNet: Automated Driver Behavior Analysis for Road Safety Using Vision-Based Systems",
      venue: "IEEE RAAICON 2025 — 4th Int'l Conference on Robotics, Automation, AI and IoT",
      badges: ["First Author", "Presented"],
      link: null,
    },
    {
      num: "04",
      title: "TOM-YOLO: Tomato Leaf Disease Detection Using Enhanced YOLOv12 Framework",
      venue: "IEEE RAAICON 2025 — 4th Int'l Conference on Robotics, Automation, AI and IoT",
      badges: ["Presented"],
      link: null,
    },
    {
      num: "05",
      title: "An Enhanced YOLOv11 Framework for Automatic Lumbar Spine Level Detection",
      venue: "IEEE ICCIT 2025 — 28th Int'l Conference on Computer and Information Technology",
      badges: ["Presented"],
      link: null,
    },
  ],

  // ── Projects ─────────────────────────────────────────────
  // For each project:
  // image: put file at assets/img/projects/<filename>
  // video: put file at assets/video/<filename> OR use a YouTube URL
  projects: [
    {
      id: "agent-bd",
      title: "Multi-Tool AI Agent (Bangladesh Data)",
      cat: "llm",
      catLabel: "LLM / NLP",
      emoji: "🤖",
      image: "assets/img/projects/agent-bd.svg",   // add your screenshot here
      video: null,
      description: "LangChain & LangGraph-based AI agent integrating multiple SQLite databases and web search APIs. Features dynamic SQL tool-calling, memory management, and structured prompt pipelines tailored for Bangladesh-specific data.",
      fullDesc: "Built a sophisticated multi-tool AI agent using LangChain and LangGraph that integrates multiple SQLite databases and web search APIs. The agent dynamically selects and calls appropriate SQL tools based on user queries, maintains conversation memory, and generates structured responses using carefully designed prompt pipelines. This project demonstrates practical LLM orchestration for domain-specific data retrieval.",
      highlights: [
        "Dynamic SQL tool-calling with schema-aware query generation",
        "Multi-database integration with LangGraph state management",
        "Web search API integration for real-time data augmentation",
        "Memory-augmented conversation handling",
        "Structured output generation with prompt optimization",
      ],
      stack: ["LangChain", "LangGraph", "SQLite", "Python", "OpenAI API"],
      github: "https://github.com/MH-SHUVO20/multi-tool-ai-agent-bd",
      demo: null,
    },
    {
      id: "yolo-api",
      title: "Bangladeshi Taka Note Detection API",
      cat: "cv",
      catLabel: "Computer Vision",
      emoji: "⚡",
      image: "assets/img/projects/yolo-api.svg",
      video: null,
      description: "Production-ready FastAPI microservice exposing a custom-trained YOLOv11 model for Bangladeshi taka note & coin detection. Returns denomination labels, confidence scores, and bounding boxes. Docker Compose bundles API with Redis caching.",
      fullDesc: "Designed and deployed a complete currency detection microservice using a custom-trained YOLOv11 model specifically for Bangladeshi taka notes and coins. The system uses FastAPI for high-performance HTTP endpoints, Redis for response caching to reduce redundant inference, and Docker Compose for one-command deployment. The live service is deployed on Render with an interactive Swagger UI for direct testing.",
      highlights: [
        "Custom YOLOv11 weights trained on Bangladeshi taka notes/coins",
        "FastAPI with Swagger UI for interactive endpoint testing",
        "Redis-backed response caching (optional locally, enabled in Compose)",
        "Docker + docker-compose for reproducible single-command startup",
        "Live deployment on Render with OpenAPI docs at /docs",
      ],
      stack: ["YOLOv11", "FastAPI", "Docker", "Redis", "Python", "PyTorch"],
      github: "https://github.com/MH-SHUVO20/Bangladeshi_taka_note_detection_api",
      demo: "https://bangladeshi-taka-note-detection-api.onrender.com/docs",
    },
    {
      id: "llm-pipeline",
      title: "LLM Article Analysis Pipeline",
      cat: "llm",
      catLabel: "LLM / NLP",
      emoji: "📄",
      image: "assets/img/projects/llm-pipeline.svg",
      video: "https://drive.google.com/file/d/1nuUUoH8o-r7B2mCnu4G__QLSFpus0GyL/preview",
      description: "Multi-stage automated AI workflow: Streamlit → FastAPI → n8n → LLM → Google Sheets → Gmail. Fully automated document analysis with structured output generation.",
      fullDesc: "Designed an end-to-end automated article analysis pipeline integrating multiple services. Documents are submitted via Streamlit UI, processed by a FastAPI backend, orchestrated through n8n workflow automation, analyzed by an LLM with optimized prompts, and results are automatically saved to Google Sheets and emailed via Gmail integration.",
      highlights: [
        "Multi-service orchestration with n8n automation",
        "OpenAI API with prompt optimization for consistent structured JSON output",
        "Automatic Google Sheets population and Gmail delivery",
        "Streamlit frontend for easy document upload and status tracking",
        "Fault-tolerant pipeline with error handling at each stage",
      ],
      stack: ["OpenAI API", "n8n", "FastAPI", "Streamlit", "Google Sheets API", "Gmail API"],
      github: "https://github.com/MH-SHUVO20/Automated-AI-Article-Analyzer",
      demo: null,
    },
    {
      id: "bert-nlp",
      title: "BERT Fine-Tuning for Question Answering",
      cat: "llm",
      catLabel: "LLM / NLP",
      emoji: "🧠",
      image: "assets/img/projects/bert-nlp.svg",
      video: null,
      description: "Fine-tuned BERT (bert-base-uncased) on SQuAD v1.1 achieving 71.15% Exact Match and 80.97% F1. Full pipeline: tokenization, span prediction, evaluation with HuggingFace Transformers and PyTorch.",
      fullDesc: "Fine-tuned a BERT (bert-base-uncased) transformer model on the Stanford Question Answering Dataset (SQuAD v1.1) for extractive question answering. The project covers the complete NLP pipeline: data preprocessing and tokenization with offset mapping, fine-tuning with the AdamW optimizer and linear scheduling, span-based answer extraction, and rigorous evaluation using Exact Match and F1-score metrics from the official SQuAD evaluation script.",
      highlights: [
        "BERT fine-tuning: 71.15% Exact Match on SQuAD v1.1",
        "80.97% F1-score with span-based answer extraction",
        "HuggingFace Transformers pipeline with PyTorch backend",
        "Offset mapping for accurate token-to-character span alignment",
        "AdamW optimizer with linear learning rate scheduling",
      ],
      stack: ["BERT", "HuggingFace", "PyTorch", "SQuAD v1.1", "Python"],
      github: "https://github.com/MH-SHUVO20/Fine-Tuning-Transformer-Models-for-Question-Answering",
      demo: null,
    },
    {
      id: "citywatch",
      title: "CityWatch — Urban Issue Reporting",
      cat: "web",
      catLabel: "Web / Systems",
      emoji: "🌆",
      image: "assets/img/projects/citywatch.svg",
      video: null,
      description: "Full-stack MVC web app with multi-role auth (Citizen, Authority, Admin), AJAX operations, RBAC, secure session handling, and relational database design.",
      fullDesc: "Built a comprehensive smart city issue reporting platform. Citizens can submit infrastructure problems with photo evidence and location tagging. Authorities can manage, respond to, and resolve reported issues. An admin panel provides full oversight. The system implements secure authentication, role-based access control, and a real-time AJAX interface for smooth user experience without full page reloads.",
      highlights: [
        "Three-tier role system: Citizen, Authority, Admin",
        "AJAX-powered dynamic UI for real-time updates",
        "RBAC with session security and XSS/SQL injection prevention",
        "Relational MySQL schema with normalized design",
        "Password hashing and prepared statements throughout",
      ],
      stack: ["PHP", "MySQL", "JavaScript", "AJAX", "HTML5", "CSS3", "MVC"],
      github: "https://github.com/MH-SHUVO20",
      demo: null,
    },
    {
      id: "medical-detection",
      title: "Medical & Disease Detection Systems",
      cat: "cv",
      catLabel: "Computer Vision",
      emoji: "🏥",
      image: "assets/img/projects/medical.svg",
      video: null,
      description: "ML/DL-based diagnostic tools for bone fracture detection (lumbar spine) and tomato leaf disease classification using enhanced YOLO frameworks.",
      fullDesc: "Developed two medical/agricultural AI systems. The first detects and classifies lumbar spine levels in X-ray images using an enhanced YOLOv11 architecture (the subject of an IEEE ICCIT paper). The second system (TOM-YOLO, IEEE RAAICON paper) classifies tomato leaf diseases in real-time using an enhanced YOLOv12 framework with custom data augmentation and transfer learning.",
      highlights: [
        "IEEE-published lumbar spine detection with YOLOv11",
        "IEEE-published tomato disease detection with YOLOv12",
        "Custom data augmentation pipelines for medical imaging",
        "Precision, Recall, F1, mAP evaluation protocols",
        "Comparison against YOLOv8/v10/v11 baseline models",
      ],
      stack: ["YOLOv11", "YOLOv12", "PyTorch", "OpenCV", "Python", "CNN"],
      github: "https://github.com/MH-SHUVO20",
      demo: null,
    },
    {
      id: "smart-house",
      title: "Smart House Rent Forecasting",
      cat: "ml",
      catLabel: "Machine Learning",
      emoji: "🏠",
      image: "assets/img/projects/house.svg",
      video: null,
      description: "Regression-based predictive system for rental price estimation using feature engineering and cross-validation techniques in Python.",
      fullDesc: "Built a machine learning pipeline for predicting rental prices in Bangladesh. The project involves comprehensive EDA, feature engineering (location encoding, property type, amenities scoring), model selection across linear regression, Random Forest, and XGBoost, and thorough cross-validation to prevent overfitting.",
      highlights: [
        "Exploratory Data Analysis with Pandas, Matplotlib, Seaborn",
        "Feature engineering: geo-encoding, amenity scoring",
        "Model comparison: Linear Regression vs RF vs XGBoost",
        "K-fold cross-validation for robust performance estimates",
        "RMSE, MAE, R² evaluation metrics",
      ],
      stack: ["Python", "Scikit-learn", "XGBoost", "Pandas", "NumPy", "Matplotlib"],
      github: "https://github.com/MH-SHUVO20",
      demo: null,
    },
    {
      id: "shuttle",
      title: "AIUB Shuttle Management System",
      cat: "web",
      catLabel: "Web / Systems",
      emoji: "🚌",
      image: "assets/img/projects/shuttle.svg",
      video: null,
      description: "Desktop scheduling and route management system built with C# and MySQL. CRUD operations, relational schema design, user authentication, and query optimization.",
      fullDesc: "Developed a comprehensive shuttle management system for AIUB campus transportation. The system handles route planning, schedule management, user reservations, and administrative oversight. Built with C# Windows Forms, MySQL backend, and features optimized database queries for fast lookups across large scheduling datasets.",
      highlights: [
        "Full CRUD for routes, schedules, and user reservations",
        "C# Windows Forms with event-driven UI",
        "MySQL with optimized queries and proper indexing",
        "User authentication with role-based access",
        "Reporting module for schedule analytics",
      ],
      stack: ["C#", "MySQL", "Windows Forms", ".NET", "SQL"],
      github: "https://github.com/MH-SHUVO20",
      demo: null,
    },
    {
      id: "linkedin-agent",
      title: "AI LinkedIn Post Generator",
      cat: "llm",
      catLabel: "LLM / NLP",
      emoji: "💼",
      image: "assets/img/projects/linkedin-agent.svg",
      video: "https://drive.google.com/file/d/1BxXIwrdv0m5u0ceLG21UqOKZtxE-Q5id/preview",
      description: "Multi-agent LangChain system with intelligent routing — classifies topics (Tech vs General) and delegates to specialized writer agents for professional, engagement-optimized LinkedIn posts in any language.",
      fullDesc: "Built an AI-powered LinkedIn content generation system using LangChain and OpenAI GPT. The architecture features a routing agent that categorizes the user's topic into Tech or General, then delegates to the appropriate specialized writer agent. Each writer produces polished, publication-ready posts with consistent quality, structured length (2–4 paragraphs), and a compelling call-to-action. Supports multiple languages including English and Bengali.",
      highlights: [
        "Multi-agent architecture: Router → Tech or General Writer",
        "Deterministic conditional routing for consistent output quality",
        "Multi-language post generation (English, Bengali, etc.)",
        "Consistent output: 2–4 paragraphs + call-to-action",
        "Modular design — easily extensible with new agent types",
      ],
      stack: ["LangChain", "OpenAI API", "Python"],
      github: "https://github.com/MH-SHUVO20/Linked-In-agent",
      demo: null,
    },
    {
      id: "churn-prediction",
      title: "Customer Churn Prediction",
      cat: "ml",
      catLabel: "Machine Learning",
      emoji: "📊",
      image: "assets/img/projects/churn-prediction.svg",
      video: null,
      description: "End-to-end ML pipeline comparing 4 classifiers (Logistic Regression, KNN, Decision Tree, Random Forest) on IBM Telco churn data (7,043 records). Random Forest achieves ~80% accuracy and 0.84 ROC-AUC.",
      fullDesc: "Built a complete churn prediction pipeline on the IBM Telco Customer Churn dataset. Performed comprehensive EDA, preprocessing (label encoding, feature scaling, stratified split), then trained and evaluated Logistic Regression, KNN, Decision Tree, and Random Forest. Used combined ROC curve plots and feature importance charts to identify contract type, tenure, and monthly charges as the top churn drivers.",
      highlights: [
        "4-model comparison: LR, KNN, Decision Tree, Random Forest",
        "Random Forest best: ~80% accuracy, ~0.84 ROC-AUC",
        "Feature importance: Contract type, tenure, monthly charges top drivers",
        "Combined ROC curve comparison across all 4 models",
        "Business analysis: minimising false negatives for proactive retention",
      ],
      stack: ["Python", "Scikit-learn", "Pandas", "NumPy", "Matplotlib", "Seaborn"],
      github: "https://github.com/MH-SHUVO20/Customer-Churn-Prediction-using-Machine-Learning",
      demo: null,
    },
    {
      id: "iris-clustering",
      title: "Unsupervised Learning on Iris Dataset",
      cat: "ml",
      catLabel: "Machine Learning",
      emoji: "🌸",
      image: "assets/img/projects/iris-clustering.svg",
      video: null,
      description: "Comprehensive unsupervised learning study applying K-Means, PCA, Hierarchical Clustering, and DBSCAN on the Iris dataset. PCA reduces 4D to 2D while retaining 95.81% of variance.",
      fullDesc: "Applied four unsupervised learning techniques on the Iris dataset. Used the Elbow Method to confirm K=3 as optimal, visualised K-Means cluster separation, reduced dimensionality via PCA (95.81% variance in 2D), compared Ward's Hierarchical clustering vs K-Means boundary quality, and tested DBSCAN for noise point detection across multiple parameter configurations. Setosa was perfectly isolated by all three algorithms.",
      highlights: [
        "Elbow Method confirms K=3 as optimal cluster count",
        "PCA: 2D retains 95.81% variance (PC1=72.96%, PC2=22.85%)",
        "Hierarchical (Ward) produces more natural boundaries than K-Means",
        "DBSCAN uniquely detects outliers K-Means silently absorbs",
        "Setosa perfectly isolated across all three clustering algorithms",
      ],
      stack: ["Python", "Scikit-learn", "SciPy", "Pandas", "NumPy", "Matplotlib", "Seaborn"],
      github: "https://github.com/MH-SHUVO20/Unsupervised-Learning-on-the-Iris-Dataset-Clustering-Algorithms-and-PCA",
      demo: null,
    },
    {
      id: "titanic-eda",
      title: "EDA on Titanic Dataset",
      cat: "ml",
      catLabel: "Machine Learning",
      emoji: "🚢",
      image: "assets/img/projects/titanic-eda.svg",
      video: null,
      description: "Structured end-to-end EDA on 891 Titanic passenger records. Gender emerged as the top survival predictor (females: 74.2% vs males: 18.9%), followed by passenger class and age.",
      fullDesc: "Conducted a systematic exploratory data analysis on the classic Titanic dataset. Workflow covered data loading, missing value treatment (median for Age, mode for Embarked, dropped Cabin at 77% missing), univariate analysis, and bivariate/multivariate cross-tabulations. Key finding: survival was strongly driven by gender (women-and-children-first protocol), socioeconomic class, and age.",
      highlights: [
        "Overall survival rate: ~38.4% of 891 passengers",
        "Top predictor: Gender (females 74.2% vs males 18.9% survival)",
        "Class effect: 1st class 63% vs 3rd class 24% survival rate",
        "Children had notably higher survival rates than elderly passengers",
        "Cherbourg embarkees had highest survival (linked to 1st-class proportion)",
      ],
      stack: ["Python", "Pandas", "NumPy", "Matplotlib", "Seaborn"],
      github: "https://github.com/MH-SHUVO20/EDA-Project",
      demo: null,
    },
    {
      id: "data-foundations",
      title: "Foundations of Data Science",
      cat: "ml",
      catLabel: "Machine Learning",
      emoji: "🧪",
      image: "assets/img/projects/data-foundations.svg",
      video: null,
      description: "Hands-on foundations project covering NumPy array operations, Pandas data manipulation, and binary classification evaluation with Logistic Regression on the Iris dataset (~73.3% accuracy).",
      fullDesc: "A comprehensive, end-to-end data science foundations notebook with 5 structured tasks. Part 1: NumPy array creation, statistical ops, broadcasting, and reshaping. Part 2: Pandas DataFrame construction, column transforms, groupby analysis, and real-world data cleaning on a 1,338-row medical insurance dataset. Part 3: binary Logistic Regression classifier on Iris with full confusion matrix and precision/recall/F1 evaluation.",
      highlights: [
        "NumPy: 1D/2D arrays, broadcasting, reshape, mean/median/std",
        "Pandas: DataFrame creation, bonus column, groupby, CSV export",
        "Data cleaning: 1,338-row insurance dataset — zero missing values",
        "Binary classification: Iris → Logistic Regression, 73.3% accuracy",
        "Full evaluation: Confusion Matrix, Precision, Recall, F1-Score",
      ],
      stack: ["Python", "NumPy", "Pandas", "Scikit-learn", "Matplotlib", "Seaborn"],
      github: "https://github.com/MH-SHUVO20/Foundations-of-Data-Science",
      demo: null,
    },
    {
      id: "california-housing",
      title: "California Housing Price Prediction",
      cat: "ml",
      catLabel: "Machine Learning",
      emoji: "🏡",
      image: "assets/img/projects/california-housing.svg",
      video: null,
      description: "Comparative regression study on the sklearn California Housing dataset. Linear, Ridge, and Lasso models compared — Lasso achieved best performance (R²=0.58, RMSE=0.74) and zeroed Population as a redundant predictor via L1 regularisation.",
      fullDesc: "Built a regression pipeline on the California Housing dataset (20,640 samples, 8 features). Applied StandardScaler preprocessing then trained and compared three models: Simple Linear Regression, Ridge (L2, alpha=1.0), and Lasso (L1, alpha=0.01). Lasso outperformed the others and zeroed out the Population coefficient — demonstrating L1's built-in feature selection capability.",
      highlights: [
        "3-model comparison: Linear Regression, Ridge (L2), Lasso (L1)",
        "Lasso best: R²=0.5816, RMSE=0.7404 — highest accuracy",
        "Lasso zeroed Population coefficient — automatic feature elimination",
        "MedInc strongest positive predictor; Latitude/Longitude most negative",
        "StandardScaler applied before all model training",
      ],
      stack: ["Python", "Scikit-learn", "Pandas", "NumPy", "Matplotlib", "Seaborn"],
      github: "https://github.com/MH-SHUVO20/Housing-Price-Prediction",
      demo: null,
    },
    {
      id: "student-mgmt",
      title: "Student Management System",
      cat: "web",
      catLabel: "Web / Systems",
      emoji: "🎓",
      image: "assets/img/projects/student-mgmt.svg",
      video: null,
      description: "Java Swing desktop application with teacher authentication, full student CRUD (Add/Update/Delete/Search by 6 fields), interactive JTable UI, and file-based data persistence. Demonstrates core OOP principles.",
      fullDesc: "Developed a Java Swing-based desktop student management system as an OOP1 course project. Features include teacher registration and login with file-based credential storage, a dashboard for managing student records, full CRUD operations with multi-field search and click-to-edit table rows, and a report submission module. The project demonstrates encapsulation, inheritance, polymorphism, event handling, and ArrayList-based data structures.",
      highlights: [
        "Teacher authentication: registration, login, session management",
        "Student CRUD: Add, Update, Delete, Search by 6 different fields",
        "Interactive JTable with click-to-edit row auto-population",
        "File I/O data persistence — no external database required",
        "Core OOP: Encapsulation, Inheritance, Polymorphism, Event Handling",
      ],
      stack: ["Java", "Swing", "AWT", "File I/O", "OOP"],
      github: "https://github.com/MH-SHUVO20/Student-Management-System",
      demo: null,
    },
    {
      id: "taka-yolo",
      title: "Bangladeshi Taka Detection — YOLOv11",
      cat: "cv",
      catLabel: "Computer Vision",
      emoji: "🇧🇩",
      image: "assets/img/projects/taka-yolo.svg",
      video: null,
      description: "End-to-end object detection project fine-tuning YOLOv11n on 11 denominations of Bangladeshi currency (notes & coins). Achieves 97.16% mAP@0.50 on ~1,490 real-world images annotated via Roboflow.",
      fullDesc: "Built a complete computer vision pipeline for real-time Bangladeshi currency recognition. Collected and annotated ~1,490 images of all 11 Taka denominations using Roboflow, then fine-tuned YOLOv11n (pretrained on COCO) for 100 epochs on a GPU (NVIDIA T4). The best checkpoint at epoch 54 achieved 97.16% mAP@0.50 with near-perfect per-class accuracy on all banknote classes. The model generalizes robustly to raw real-world mobile camera images under diverse lighting, angles, and backgrounds — making it viable for edge and mobile deployment.",
      highlights: [
        "97.16% mAP@0.50 at epoch 54 — nano-scale model (~2.6M parameters)",
        "7 of 11 denomination classes hit 100% detection accuracy",
        "Transfer learning from COCO: mAP jumped from 48% (epoch 1) to 97% (epoch 54)",
        "No significant overfitting — clean loss convergence across 100 epochs",
        "Validated on 40 raw unannotated real-world mobile camera images",
      ],
      stack: ["YOLOv11", "Ultralytics", "PyTorch", "Roboflow", "Python", "Colab"],
      github: "https://github.com/MH-SHUVO20/Bangladeshi_Taka_Note_Detection_Using_YOLOv11",
      demo: null,
    },
    {
      id: "cifar10",
      title: "CIFAR-10 Image Classifier — Deep MLP",
      cat: "cv",
      catLabel: "Computer Vision",
      emoji: "🔢",
      image: "assets/img/projects/cifar10.svg",
      video: null,
      description: "Deep MLP (Dense Neural Network) trained on CIFAR-10 to classify 60K images across 10 categories. Achieves 48.14% test accuracy using Batch Normalization and Dropout — a foundational baseline study in deep learning.",
      fullDesc: "Designed and trained a 4-layer Dense Neural Network (MLP) on the CIFAR-10 benchmark to establish a baseline accuracy for fully-connected architectures on image data. The model uses 512→256→128→64 hidden layers with Batch Normalization after each layer and Dropout regularization (0.3, 0.3, 0.2) to reduce overfitting. Trained for 20 epochs with Adam optimizer. The 48.14% test accuracy confirms the theoretical ceiling for MLPs on spatial image data, motivating the need for convolutional architectures.",
      highlights: [
        "4-layer Dense MLP: 512 → 256 → 128 → 64 → 10-class Softmax",
        "48.14% test accuracy — theoretical MLP ceiling on CIFAR-10",
        "Batch Normalization stabilizes gradient flow across all hidden layers",
        "Dropout (0.3/0.3/0.2) reduces overfitting on spatially rich image data",
        "Establishes baseline motivating CNN adoption for image classification",
      ],
      stack: ["TensorFlow", "Keras", "Python", "NumPy", "Matplotlib"],
      github: "https://github.com/MH-SHUVO20/Deep-Learning-Project-CIFAR-10-Image-Classifier",
      demo: null,
    },
    {
      id: "nn-vs-cnn",
      title: "NN vs CNN — CIFAR-10 Comparison",
      cat: "cv",
      catLabel: "Computer Vision",
      emoji: "⚔️",
      image: "assets/img/projects/nn-vs-cnn.svg",
      video: null,
      description: "Head-to-head experiment training a plain Neural Network (48.27%) against a CNN (69.12%) on CIFAR-10 under identical conditions — demonstrating the +20.85 pp advantage of spatial feature learning over flattened pixels.",
      fullDesc: "Designed a controlled experiment to quantify the performance gap between a fully-connected Neural Network and a Convolutional Neural Network on the CIFAR-10 image classification benchmark. Both models are trained under identical conditions (Adam optimizer, 15 epochs, batch 64, 20% validation split). The NN flattens images to 3,072-dimensional vectors losing all spatial structure; the CNN preserves the 32×32×3 shape and learns local edges, textures, and shapes via convolutions. The 20.85 percentage-point gap directly demonstrates why CNNs were invented for image data.",
      highlights: [
        "CNN (69.12%) beats NN (48.27%) by +20.85 pp on identical training setup",
        "NN: Dense(280) → Dense(120) → Softmax — flattened input loses spatial structure",
        "CNN: Conv2D(28) → Pool → Conv2D(56) → Pool → Conv2D(112) → Dense(180)",
        "CNN validation accuracy climbs steadily; NN plateaus after just a few epochs",
        "CNN requires fewer parameters yet achieves dramatically higher accuracy",
      ],
      stack: ["TensorFlow", "Keras", "Python", "NumPy", "Matplotlib"],
      github: "https://github.com/MH-SHUVO20/Mini-Project-Image-Classification-using-NN-vs-CNN",
      demo: null,
    },
    {
      id: "imdb-sentiment",
      title: "Sentiment Analysis — IMDB Reviews",
      cat: "llm",
      catLabel: "LLM / NLP",
      emoji: "🎬",
      image: "assets/img/projects/imdb-sentiment.svg",
      video: null,
      description: "Comprehensive comparative study of 4 sentiment models on 50K IMDB reviews: TF-IDF + LogReg, Word2Vec, BERT Embeddings, and Fine-tuned BERT. Benchmarks accuracy, F1, and computational trade-offs across all approaches.",
      fullDesc: "Conducted a rigorous comparative analysis of sentiment classification techniques on the IMDB movie reviews dataset (50,000 samples). Four distinct approaches are evaluated: (1) TF-IDF with Logistic Regression — fast CPU-only baseline; (2) Word2Vec averaged embeddings with Logistic Regression; (3) BERT (bert-base-uncased) CLS token features with Logistic Regression; (4) End-to-end fine-tuned BERT for sequence classification. Results show fine-tuned BERT achieves the highest accuracy and F1, while TF-IDF provides a compelling production-ready baseline with dramatically lower compute cost.",
      highlights: [
        "Fine-tuned BERT achieves highest accuracy & F1 (2 epochs, AdamW lr=2e-5)",
        "TF-IDF+LogReg: strong baseline, CPU-only, trains in 2-5 minutes",
        "Word2Vec (dim=100, window=5): moderate performance; weak on negation",
        "BERT CLS embeddings: higher contextual quality than Word2Vec",
        "Full comparison: Accuracy, Precision, Recall, F1, training time analysis",
      ],
      stack: ["BERT", "HuggingFace", "PyTorch", "Scikit-learn", "Gensim", "Python"],
      github: "https://github.com/MH-SHUVO20/Sentiment-Analysis-on-IMDB-Movie-Reviews",
      demo: null,
    },
  ],

  // ── Education ─────────────────────────────────────────────
  education: [
    {
      year: "2022 — 2026 (Expected)",
      degree: "B.Sc. in Computer Science & Engineering",
      major: "Major: Information Systems",
      institution: "American International University–Bangladesh (AIUB), Dhaka",
      gpa: "CGPA: 3.75 / 4.00",
      desc: "Pursuing undergraduate studies with a focus on AI, Machine Learning, Computer Vision, and Deep Learning. Active researcher and IEEE student member throughout the program.",
      courses: ["Data Structures & Algorithms", "Machine Learning", "NLP", "Computer Vision", "Software Engineering", "Database Systems", "Data Warehousing & Mining", "OOP", "Operating Systems"],
    },
    {
      year: "2018 — 2020",
      degree: "Higher Secondary Certificate (Science)",
      major: "",
      institution: "Govt. Keshab Chandra College, Jhenaidah",
      gpa: "GPA: 5.00 / 5.00",
      desc: "Achieved perfect GPA in the science stream, with strong foundation in Mathematics and Physics.",
      courses: ["Higher Mathematics", "Physics", "Chemistry", "Biology", "English", "Bangla", "ICT"],
    },
    {
      year: "2016 — 2018",
      degree: "Secondary School Certificate (Science)",
      major: "",
      institution: "Garagonj High School",
      gpa: "GPA: 4.67 / 5.00",
      desc: "Completed secondary education in the science stream with a strong foundation in Mathematics, Physics, and Chemistry.",
      courses: ["Mathematics", "Physics", "Chemistry", "Biology", "English", "Bangla", "ICT", "Higher Mathematics", "Bangladesh and Global Studies", "Islamic Studies"],
    },
  ],

  // ── Experience ────────────────────────────────────────────
  experience: [
    {
      role: "AI Researcher",
      org: "American International University–Bangladesh (AIUB)",
      period: "2024 — Present",
      type: "Research",
      icon: "fas fa-flask",
      colorClass: "exp-color-blue",
      desc: "Conducting independent and collaborative research in Computer Vision and Deep Learning at AIUB. Published 5 IEEE papers at internationally ranked conference venues within 2 years, covering YOLO-based systems, medical imaging, and driver behavior analysis.",
      highlights: [
        "5 IEEE publications at CORE-ranked & international venues",
        "Presented at AICCSA 2025, ECCE 2025, RAAICON 2025, ICCIT 2025",
        "Research areas: YOLO, LLMs, NLP, Medical AI, Driver AI",
        "Collaborated with faculty advisors on deep learning projects",
      ],
    },
    {
      role: "IEEE Conference Reviewer",
      org: "IEEE — 3ICT 2025 & FET'26",
      period: "2025 — Present",
      type: "Academic Service",
      icon: "fas fa-search",
      colorClass: "exp-color-purple",
      desc: "Serving as an active peer reviewer for IEEE international conferences, evaluating manuscript quality, technical rigor, novelty, and research contributions in deep learning, intelligent systems, and applied AI domains.",
      highlights: [
        "Reviewer for IEEE 3ICT 2025 (International Conference on Innovation and Intelligence)",
        "Assigned to IEEE FET'26 review committee",
        "Domains: Deep Learning, AI Systems, Computer Vision, IoT",
      ],
    },
    {
      role: "Private Tutor & Education Consultant",
      org: "Independent · Dhaka, Bangladesh",
      period: "2019 — Present",
      type: "Teaching",
      icon: "fas fa-chalkboard-teacher",
      colorClass: "exp-color-green",
      desc: "Providing comprehensive academic tutoring for students from Class 6 through HSC and O/A Level programs for 6+ years. Co-managed a coaching center serving 500+ students. Specialized in science subjects, mathematics, and computer science.",
      highlights: [
        "6+ years of full-time and part-time teaching experience",
        "4+ years in English medium instruction",
        "Co-managed coaching center with 500+ enrolled students",
        "O Level, A Level, SSC & HSC exam preparation",
        "Subjects: Physics, Chemistry, Math, Biology, CS, English, Bangla",
      ],
    },
  ],
  // ── Certifications ─────────────────────────────────────
  certs: [
    {
      title: "IEEE Student Member Certificate",
      issuer: "IEEE",
      category: "Membership",
      icon: "fas fa-id-card",
      color: "cert-blue",
      year: "2023",
      file: "Certificate/MEMIEEE500.pdf",
    },
    {
      title: "IEEE Computer Society Member Certificate",
      issuer: "IEEE Computer Society",
      category: "Membership",
      icon: "fas fa-laptop-code",
      color: "cert-blue",
      year: "2023",
      file: "Certificate/MEMC016.pdf",
    },
    {
      title: "IEEE 3ICT 2025 — Conference Certificate",
      issuer: "IEEE — 3ICT 2025",
      category: "Academic Service",
      icon: "fas fa-users",
      color: "cert-purple",
      year: "2025",
      file: "Certificate/3ict2025-certificate.pdf",
    },
    {
      title: "IEEE Member Certificate",
      issuer: "IEEE",
      category: "Membership",
      icon: "fas fa-certificate",
      color: "cert-blue",
      year: "2023",
      file: "Certificate/101019814.pdf",
    },
    {
      title: "ECCE 2025 — Author Certificate",
      issuer: "IEEE ECCE 2025",
      category: "Conference Author",
      icon: "fas fa-car",
      color: "cert-cyan",
      year: "2025",
      file: "Certificate/ECCE 2025 Author Certificate.pdf",
    },
    {
      title: "RAAICON 2025 — Author Certificate (DBNet)",
      issuer: "IEEE RAAICON 2025",
      category: "Conference Author",
      icon: "fas fa-car",
      color: "cert-purple",
      year: "2025",
      file: "Certificate/Dbnet Raiccon_Author Certificate.jpg",
    },
    {
      title: "RAAICON 2025 — Author Certificate (TOM-YOLO)",
      issuer: "IEEE RAAICON 2025",
      category: "Conference Author",
      icon: "fas fa-leaf",
      color: "cert-green",
      year: "2025",
      file: "Certificate/TomYolo_ Raiccon_Author Certificate.jpg",
    },
    {
      title: "ICCIT 2025 — Author Certificate",
      issuer: "IEEE ICCIT 2025",
      category: "Conference Author",
      icon: "fas fa-x-ray",
      color: "cert-blue",
      year: "2025",
      file: "Certificate/ICCIT Author Certificate.jpg",
    },
    {
      title: "Certified Tutor",
      issuer: "CareTutors",
      category: "Teaching",
      icon: "fas fa-chalkboard-teacher",
      color: "cert-green",
      year: "2025",
      file: "Certificate/caretutors_certificate_272420.pdf",
    },
    {
      title: "IT Essentials — Cisco Official Certificate",
      issuer: "Cisco Networking Academy",
      category: "Course Completion",
      icon: "fas fa-network-wired",
      color: "cert-blue",
      year: "2022",
      file: "Certificate/MD MEHEDI HASANSHUVO-INTRODUCTION TO -certificate.pdf",
    },
    {
      title: "IT Essentials — Academy Certificate",
      issuer: "Cisco Networking Academy · AIUB",
      category: "Course Completion",
      icon: "fas fa-laptop",
      color: "cert-blue",
      year: "2022",
      file: "Certificate/MD MEHEDI HASANSHUVO-INTRODUCTION TO -certificate_2.pdf",
    },
  ],
  // ── Contact ───────────────────────────────────────────────
  contactLinks: [
    { icon: "fas fa-envelope", label: "Email", value: "mdmehedihasanshuvo994@gmail.com", href: "mailto:mdmehedihasanshuvo994@gmail.com" },
    { icon: "fab fa-linkedin", label: "LinkedIn", value: "linkedin.com/in/mh-shuvo-aiub", href: "https://linkedin.com/in/mh-shuvo-aiub/" },
    { icon: "fab fa-github", label: "GitHub", value: "github.com/MH-SHUVO20", href: "https://github.com/MH-SHUVO20" },
    { icon: "fas fa-globe", label: "Portfolio", value: "mhshuvo.me", href: "https://mhshuvo.me/" },
    { icon: "fas fa-phone", label: "Phone", value: "+8801954-596854", href: "tel:+8801954596854" },
    { icon: "fab fa-facebook", label: "Facebook", value: "mh.shuvo.7370", href: "https://www.facebook.com/mh.shuvo.7370" },
  ],
};
