name: Deploy static site to GitHub Pages

on:
  push:
    branches:
      - main  # Change this to your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # Ensure this is compatible with your project

    - name: Install dependencies
      run: npm install
      working-directory: ./path/to/your/project  # Adjust this if your project is not in the root directory

    - name: Build the site
      run: npm run build # Adjust this command to your build script
      working-directory: ./path/to/your/project  # Adjust this if your project is not in the root directory

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public  # Adjust this to your build output directory
